### ISSUE TITLE
Segfault for verifyModule() on Function

### ISSUE THREAD

**Issue by nick-ulle** [duncantl/Rllvm#10]
This causes a segfault:
```{r}
library(Rllvm)

foo = Function("foo", VoidType, list())
verifyModule(foo)
```
This is under LLVM 3.6.2 and the latest commit of Rllvm.

This is not an urgent issue, but a warning message or implicit call to `getParent()` would be nicer than a segfault.

**Comment by duncantl** [comment]
Fixed now. Simple as(module, "Module") addition.
